//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGvwClasificadorObjetoGasto
    {
        public int COGCodigo { get; set; }
        public string COG { get; set; }
        public string CuentaAlmacenCodigo { get; set; }
        public string CuentaAlmacen { get; set; }
        public string CuentaGastoCodigo { get; set; }
        public string CuentaGasto { get; set; }
    }
}
