//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisicionesAlmacenBL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolizaRef
    {
        public int PolizaRefId { get; set; }
        public int PolizaId { get; set; }
        public int TipoMovimientoId { get; set; }
        public string Tipo { get; set; }
        public int Referencia { get; set; }
    
        public virtual tblPoliza tblPoliza { get; set; }
    }
}
